<a href="https://colab.research.google.com/github/imdatkris/texasdaprogram/blob/main/custDemoClass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [32]:
data = pd.read_csv('/content/sample_data/Demographic_Data.csv')

In [19]:
from sklearn.datasets import load_digits

In [21]:
digits = load_digits()

In [22]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [23]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [26]:
import numpy as np
import pandas as pd
import pandas_profiling
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

%matplotlib inline

In [30]:
testdata = pd.read_csv('/content/sample_data/testdata.csv')

In [31]:
traindata = pd.read_csv('/content/sample_data/traindata.csv')

In [33]:
data[0:3]

in-store  age  items   amount  region
0         0   37      4   281.03       2
1         0   35      2   219.51       2
2         1   45      3  1525.70       4

In [34]:
data[26:31]

in-store  age  items   amount  region
26         0   42      5   114.49       2
27         1   40      5  1151.70       4
28         1   31      4   246.61       3
29         0   28      7   623.05       4
30         1   59      3   346.26       1

In [35]:
in_store = data['in-store']

In [37]:
#features
X = data.iloc[:,0:4]
print('Summary of feature sample')
X.head()

Summary of feature sample


in-store  age  items   amount
0         0   37      4   281.03
1         0   35      2   219.51
2         1   45      3  1525.70
3         1   46      3   715.25
4         1   33      4  1937.50

In [38]:
#dependent variable
y = data['region']